version: '3.8'
services:
  openapi-codegen:
    image: openapitools/openapi-generator-cli:v6.2.1
    volumes:
      - .:/local
    working_dir: /local
    command:
      - generate
      - -i
      - /local/openapi.yml
      - -o
      - /local/api/typescript-fetch
      - -g
      - typescript-fetch
      - --additional-properties
      - typescriptThreePlus=true
  scripts:
    image: golang:1.19-alpine
    volumes:
      - .:/local
    working_dir: /local
    entrypoint:
      - go
      - run
