=begin
#Cordial

#A cooperative word puzzle game!

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
OpenapiClient.autoload :Account, 'openapi_client/models/account'
OpenapiClient.autoload :CreateGameProps, 'openapi_client/models/create_game_props'
OpenapiClient.autoload :CreateGuessProps, 'openapi_client/models/create_guess_props'
OpenapiClient.autoload :CreateUserProps, 'openapi_client/models/create_user_props'
OpenapiClient.autoload :Game, 'openapi_client/models/game'
OpenapiClient.autoload :Guess, 'openapi_client/models/guess'
OpenapiClient.autoload :LoginProps, 'openapi_client/models/login_props'
OpenapiClient.autoload :PublicKeyResponse, 'openapi_client/models/public_key_response'
OpenapiClient.autoload :Subscription, 'openapi_client/models/subscription'
OpenapiClient.autoload :SubscriptionKeys, 'openapi_client/models/subscription_keys'
OpenapiClient.autoload :Token, 'openapi_client/models/token'
OpenapiClient.autoload :UnsubscribeProps, 'openapi_client/models/unsubscribe_props'
OpenapiClient.autoload :User, 'openapi_client/models/user'

# APIs
OpenapiClient.autoload :AuthApi, 'openapi_client/api/auth_api'
OpenapiClient.autoload :GamesApi, 'openapi_client/api/games_api'
OpenapiClient.autoload :NotificationsApi, 'openapi_client/api/notifications_api'
OpenapiClient.autoload :UsersApi, 'openapi_client/api/users_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
