=begin
#Cordial

#A cooperative word puzzle game!

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::CreateGameProps
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::CreateGameProps do
  let(:instance) { OpenapiClient::CreateGameProps.new }

  describe 'test an instance of CreateGameProps' do
    it 'should create an instance of CreateGameProps' do
      expect(instance).to be_instance_of(OpenapiClient::CreateGameProps)
    end
  end
  describe 'test attribute "acceptor_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
