=begin
#Cordial

#A cooperative word puzzle game!

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Cordial::UnsubscribeProps
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Cordial::UnsubscribeProps do
  let(:instance) { Cordial::UnsubscribeProps.new }

  describe 'test an instance of UnsubscribeProps' do
    it 'should create an instance of UnsubscribeProps' do
      expect(instance).to be_instance_of(Cordial::UnsubscribeProps)
    end
  end
  describe 'test attribute "push_token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "endpoint"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
