/*
Cordial

A cooperative word puzzle game!

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cordial

import (
	"encoding/json"
)

// CreateGuessProps struct for CreateGuessProps
type CreateGuessProps struct {
	Word string `json:"word"`
}

// NewCreateGuessProps instantiates a new CreateGuessProps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGuessProps(word string) *CreateGuessProps {
	this := CreateGuessProps{}
	this.Word = word
	return &this
}

// NewCreateGuessPropsWithDefaults instantiates a new CreateGuessProps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGuessPropsWithDefaults() *CreateGuessProps {
	this := CreateGuessProps{}
	return &this
}

// GetWord returns the Word field value
func (o *CreateGuessProps) GetWord() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Word
}

// GetWordOk returns a tuple with the Word field value
// and a boolean to check if the value has been set.
func (o *CreateGuessProps) GetWordOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Word, true
}

// SetWord sets field value
func (o *CreateGuessProps) SetWord(v string) {
	o.Word = v
}

func (o CreateGuessProps) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["word"] = o.Word
	}
	return json.Marshal(toSerialize)
}

type NullableCreateGuessProps struct {
	value *CreateGuessProps
	isSet bool
}

func (v NullableCreateGuessProps) Get() *CreateGuessProps {
	return v.value
}

func (v *NullableCreateGuessProps) Set(val *CreateGuessProps) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGuessProps) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGuessProps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGuessProps(val *CreateGuessProps) *NullableCreateGuessProps {
	return &NullableCreateGuessProps{value: val, isSet: true}
}

func (v NullableCreateGuessProps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGuessProps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


