/*
Cordial

A cooperative word puzzle game!

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UnsubscribeProps struct for UnsubscribeProps
type UnsubscribeProps struct {
	PushToken *string `json:"pushToken,omitempty"`
	Endpoint *string `json:"endpoint,omitempty"`
}

// NewUnsubscribeProps instantiates a new UnsubscribeProps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnsubscribeProps() *UnsubscribeProps {
	this := UnsubscribeProps{}
	return &this
}

// NewUnsubscribePropsWithDefaults instantiates a new UnsubscribeProps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnsubscribePropsWithDefaults() *UnsubscribeProps {
	this := UnsubscribeProps{}
	return &this
}

// GetPushToken returns the PushToken field value if set, zero value otherwise.
func (o *UnsubscribeProps) GetPushToken() string {
	if o == nil || o.PushToken == nil {
		var ret string
		return ret
	}
	return *o.PushToken
}

// GetPushTokenOk returns a tuple with the PushToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsubscribeProps) GetPushTokenOk() (*string, bool) {
	if o == nil || o.PushToken == nil {
		return nil, false
	}
	return o.PushToken, true
}

// HasPushToken returns a boolean if a field has been set.
func (o *UnsubscribeProps) HasPushToken() bool {
	if o != nil && o.PushToken != nil {
		return true
	}

	return false
}

// SetPushToken gets a reference to the given string and assigns it to the PushToken field.
func (o *UnsubscribeProps) SetPushToken(v string) {
	o.PushToken = &v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *UnsubscribeProps) GetEndpoint() string {
	if o == nil || o.Endpoint == nil {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnsubscribeProps) GetEndpointOk() (*string, bool) {
	if o == nil || o.Endpoint == nil {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *UnsubscribeProps) HasEndpoint() bool {
	if o != nil && o.Endpoint != nil {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *UnsubscribeProps) SetEndpoint(v string) {
	o.Endpoint = &v
}

func (o UnsubscribeProps) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PushToken != nil {
		toSerialize["pushToken"] = o.PushToken
	}
	if o.Endpoint != nil {
		toSerialize["endpoint"] = o.Endpoint
	}
	return json.Marshal(toSerialize)
}

type NullableUnsubscribeProps struct {
	value *UnsubscribeProps
	isSet bool
}

func (v NullableUnsubscribeProps) Get() *UnsubscribeProps {
	return v.value
}

func (v *NullableUnsubscribeProps) Set(val *UnsubscribeProps) {
	v.value = val
	v.isSet = true
}

func (v NullableUnsubscribeProps) IsSet() bool {
	return v.isSet
}

func (v *NullableUnsubscribeProps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnsubscribeProps(val *UnsubscribeProps) *NullableUnsubscribeProps {
	return &NullableUnsubscribeProps{value: val, isSet: true}
}

func (v NullableUnsubscribeProps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnsubscribeProps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


