/*
Cordial

A cooperative word puzzle game!

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cordial

import (
	"encoding/json"
)

// PublicKeyResponse struct for PublicKeyResponse
type PublicKeyResponse struct {
	PublicKey string `json:"publicKey"`
}

// NewPublicKeyResponse instantiates a new PublicKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicKeyResponse(publicKey string) *PublicKeyResponse {
	this := PublicKeyResponse{}
	this.PublicKey = publicKey
	return &this
}

// NewPublicKeyResponseWithDefaults instantiates a new PublicKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicKeyResponseWithDefaults() *PublicKeyResponse {
	this := PublicKeyResponse{}
	return &this
}

// GetPublicKey returns the PublicKey field value
func (o *PublicKeyResponse) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *PublicKeyResponse) GetPublicKeyOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *PublicKeyResponse) SetPublicKey(v string) {
	o.PublicKey = v
}

func (o PublicKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["publicKey"] = o.PublicKey
	}
	return json.Marshal(toSerialize)
}

type NullablePublicKeyResponse struct {
	value *PublicKeyResponse
	isSet bool
}

func (v NullablePublicKeyResponse) Get() *PublicKeyResponse {
	return v.value
}

func (v *NullablePublicKeyResponse) Set(val *PublicKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicKeyResponse(val *PublicKeyResponse) *NullablePublicKeyResponse {
	return &NullablePublicKeyResponse{value: val, isSet: true}
}

func (v NullablePublicKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


