/*
Cordial

A cooperative word puzzle game!

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cordial

import (
	"encoding/json"
	"time"
)

// Guess struct for Guess
type Guess struct {
	Id *int64 `json:"id,omitempty"`
	DiscardedAt NullableTime `json:"discardedAt,omitempty"`
	Word *string `json:"word,omitempty"`
	GameId *int64 `json:"gameId,omitempty"`
	Comparison []int32 `json:"comparison,omitempty"`
}

// NewGuess instantiates a new Guess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuess() *Guess {
	this := Guess{}
	return &this
}

// NewGuessWithDefaults instantiates a new Guess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuessWithDefaults() *Guess {
	this := Guess{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Guess) GetId() int64 {
	if o == nil || isNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Guess) GetIdOk() (*int64, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Guess) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *Guess) SetId(v int64) {
	o.Id = &v
}

// GetDiscardedAt returns the DiscardedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Guess) GetDiscardedAt() time.Time {
	if o == nil || isNil(o.DiscardedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DiscardedAt.Get()
}

// GetDiscardedAtOk returns a tuple with the DiscardedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Guess) GetDiscardedAtOk() (*time.Time, bool) {
	if o == nil {
    return nil, false
	}
	return o.DiscardedAt.Get(), o.DiscardedAt.IsSet()
}

// HasDiscardedAt returns a boolean if a field has been set.
func (o *Guess) HasDiscardedAt() bool {
	if o != nil && o.DiscardedAt.IsSet() {
		return true
	}

	return false
}

// SetDiscardedAt gets a reference to the given NullableTime and assigns it to the DiscardedAt field.
func (o *Guess) SetDiscardedAt(v time.Time) {
	o.DiscardedAt.Set(&v)
}
// SetDiscardedAtNil sets the value for DiscardedAt to be an explicit nil
func (o *Guess) SetDiscardedAtNil() {
	o.DiscardedAt.Set(nil)
}

// UnsetDiscardedAt ensures that no value is present for DiscardedAt, not even an explicit nil
func (o *Guess) UnsetDiscardedAt() {
	o.DiscardedAt.Unset()
}

// GetWord returns the Word field value if set, zero value otherwise.
func (o *Guess) GetWord() string {
	if o == nil || isNil(o.Word) {
		var ret string
		return ret
	}
	return *o.Word
}

// GetWordOk returns a tuple with the Word field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Guess) GetWordOk() (*string, bool) {
	if o == nil || isNil(o.Word) {
    return nil, false
	}
	return o.Word, true
}

// HasWord returns a boolean if a field has been set.
func (o *Guess) HasWord() bool {
	if o != nil && !isNil(o.Word) {
		return true
	}

	return false
}

// SetWord gets a reference to the given string and assigns it to the Word field.
func (o *Guess) SetWord(v string) {
	o.Word = &v
}

// GetGameId returns the GameId field value if set, zero value otherwise.
func (o *Guess) GetGameId() int64 {
	if o == nil || isNil(o.GameId) {
		var ret int64
		return ret
	}
	return *o.GameId
}

// GetGameIdOk returns a tuple with the GameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Guess) GetGameIdOk() (*int64, bool) {
	if o == nil || isNil(o.GameId) {
    return nil, false
	}
	return o.GameId, true
}

// HasGameId returns a boolean if a field has been set.
func (o *Guess) HasGameId() bool {
	if o != nil && !isNil(o.GameId) {
		return true
	}

	return false
}

// SetGameId gets a reference to the given int64 and assigns it to the GameId field.
func (o *Guess) SetGameId(v int64) {
	o.GameId = &v
}

// GetComparison returns the Comparison field value if set, zero value otherwise.
func (o *Guess) GetComparison() []int32 {
	if o == nil || isNil(o.Comparison) {
		var ret []int32
		return ret
	}
	return o.Comparison
}

// GetComparisonOk returns a tuple with the Comparison field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Guess) GetComparisonOk() ([]int32, bool) {
	if o == nil || isNil(o.Comparison) {
    return nil, false
	}
	return o.Comparison, true
}

// HasComparison returns a boolean if a field has been set.
func (o *Guess) HasComparison() bool {
	if o != nil && !isNil(o.Comparison) {
		return true
	}

	return false
}

// SetComparison gets a reference to the given []int32 and assigns it to the Comparison field.
func (o *Guess) SetComparison(v []int32) {
	o.Comparison = v
}

func (o Guess) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.DiscardedAt.IsSet() {
		toSerialize["discardedAt"] = o.DiscardedAt.Get()
	}
	if !isNil(o.Word) {
		toSerialize["word"] = o.Word
	}
	if !isNil(o.GameId) {
		toSerialize["gameId"] = o.GameId
	}
	if !isNil(o.Comparison) {
		toSerialize["comparison"] = o.Comparison
	}
	return json.Marshal(toSerialize)
}

type NullableGuess struct {
	value *Guess
	isSet bool
}

func (v NullableGuess) Get() *Guess {
	return v.value
}

func (v *NullableGuess) Set(val *Guess) {
	v.value = val
	v.isSet = true
}

func (v NullableGuess) IsSet() bool {
	return v.isSet
}

func (v *NullableGuess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuess(val *Guess) *NullableGuess {
	return &NullableGuess{value: val, isSet: true}
}

func (v NullableGuess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// CUSTOM_CODE_HOOK
