/*
Cordial

A cooperative word puzzle game!

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cordial

import (
	"encoding/json"
)

// CreateGameProps struct for CreateGameProps
type CreateGameProps struct {
	AcceptorId string `json:"acceptorId"`
}

// NewCreateGameProps instantiates a new CreateGameProps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGameProps(acceptorId string) *CreateGameProps {
	this := CreateGameProps{}
	this.AcceptorId = acceptorId
	return &this
}

// NewCreateGamePropsWithDefaults instantiates a new CreateGameProps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGamePropsWithDefaults() *CreateGameProps {
	this := CreateGameProps{}
	return &this
}

// GetAcceptorId returns the AcceptorId field value
func (o *CreateGameProps) GetAcceptorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AcceptorId
}

// GetAcceptorIdOk returns a tuple with the AcceptorId field value
// and a boolean to check if the value has been set.
func (o *CreateGameProps) GetAcceptorIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.AcceptorId, true
}

// SetAcceptorId sets field value
func (o *CreateGameProps) SetAcceptorId(v string) {
	o.AcceptorId = v
}

func (o CreateGameProps) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["acceptorId"] = o.AcceptorId
	}
	return json.Marshal(toSerialize)
}

type NullableCreateGameProps struct {
	value *CreateGameProps
	isSet bool
}

func (v NullableCreateGameProps) Get() *CreateGameProps {
	return v.value
}

func (v *NullableCreateGameProps) Set(val *CreateGameProps) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGameProps) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGameProps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGameProps(val *CreateGameProps) *NullableCreateGameProps {
	return &NullableCreateGameProps{value: val, isSet: true}
}

func (v NullableCreateGameProps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGameProps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

// CUSTOM_CODE_HOOK
