/* tslint:disable */
/* eslint-disable */
/**
 * Cordial
 * A cooperative word puzzle game!
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGameProps
 */
export interface CreateGameProps {
    /**
     * 
     * @type {string}
     * @memberof CreateGameProps
     */
    acceptorId: string;
}

/**
 * Check if a given object implements the CreateGameProps interface.
 */
export function instanceOfCreateGameProps(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "acceptorId" in value;

    return isInstance;
}

export function CreateGamePropsFromJSON(json: any): CreateGameProps {
    return CreateGamePropsFromJSONTyped(json, false);
}

export function CreateGamePropsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGameProps {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'acceptorId': json['acceptorId'],
    };
}

export function CreateGamePropsToJSON(value?: CreateGameProps | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'acceptorId': value.acceptorId,
    };
}

