/* tslint:disable */
/* eslint-disable */
/**
 * Cordial
 * A cooperative word puzzle game!
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicKeyResponse
 */
export interface PublicKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof PublicKeyResponse
     */
    publicKey: string;
}

/**
 * Check if a given object implements the PublicKeyResponse interface.
 */
export function instanceOfPublicKeyResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "publicKey" in value;

    return isInstance;
}

export function PublicKeyResponseFromJSON(json: any): PublicKeyResponse {
    return PublicKeyResponseFromJSONTyped(json, false);
}

export function PublicKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicKeyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'publicKey': json['publicKey'],
    };
}

export function PublicKeyResponseToJSON(value?: PublicKeyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'publicKey': value.publicKey,
    };
}

