=begin
#Cordial

#A cooperative word puzzle game!

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Cordial::GamesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GamesApi' do
  before do
    # run before each test
    @api_instance = Cordial::GamesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GamesApi' do
    it 'should create an instance of GamesApi' do
      expect(@api_instance).to be_instance_of(Cordial::GamesApi)
    end
  end

  # unit tests for create_game
  # Creates a new game.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateGameProps] :create_game_props 
  # @return [Game]
  describe 'create_game test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_guess
  # Make a guess for the specified game.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [CreateGuessProps] :create_guess_props 
  # @return [Game]
  describe 'create_guess test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_game
  # Deletes the specified game.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Game]
  describe 'delete_game test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_game
  # Returns the specified game.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Game]
  describe 'get_game test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_games
  # Returns all accessible games.
  # @param [Hash] opts the optional parameters
  # @return [Array<Game>]
  describe 'list_games test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
