=begin
#Cordial

#A cooperative word puzzle game!

The version of the OpenAPI document: 0.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for Cordial::NotificationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'NotificationsApi' do
  before do
    # run before each test
    @api_instance = Cordial::NotificationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NotificationsApi' do
    it 'should create an instance of NotificationsApi' do
      expect(@api_instance).to be_instance_of(Cordial::NotificationsApi)
    end
  end

  # unit tests for get_public_key
  # Get VAPID public key.
  # @param [Hash] opts the optional parameters
  # @return [PublicKeyResponse]
  describe 'get_public_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for subscribe
  # Subscribe to WebPush notifications.
  # @param [Hash] opts the optional parameters
  # @option opts [Subscription] :subscription 
  # @return [Object]
  describe 'subscribe test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for unsubscribe
  # Unsubscribe from WebPush notifications.
  # @param [Hash] opts the optional parameters
  # @option opts [UnsubscribeProps] :unsubscribe_props 
  # @return [Object]
  describe 'unsubscribe test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
