/* tslint:disable */
/* eslint-disable */
/**
 * Cordial
 * A cooperative word puzzle game!
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionKeys
 */
export interface SubscriptionKeys {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionKeys
     */
    auth: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionKeys
     */
    p256dh: string;
}

/**
 * Check if a given object implements the SubscriptionKeys interface.
 */
export function instanceOfSubscriptionKeys(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "auth" in value;
    isInstance = isInstance && "p256dh" in value;

    return isInstance;
}

export function SubscriptionKeysFromJSON(json: any): SubscriptionKeys {
    return SubscriptionKeysFromJSONTyped(json, false);
}

export function SubscriptionKeysFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionKeys {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'auth': json['auth'],
        'p256dh': json['p256dh'],
    };
}

export function SubscriptionKeysToJSON(value?: SubscriptionKeys | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auth': value.auth,
        'p256dh': value.p256dh,
    };
}

// CUSTOM_CODE_HOOK
