/* tslint:disable */
/* eslint-disable */
/**
 * Cordial
 * A cooperative word puzzle game!
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     * @type {number}
     * @memberof Token
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Token
     */
    discardedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Token
     */
    accessToken?: string;
}

/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenFromJSON(json: any): Token {
    return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'discardedAt': !exists(json, 'discardedAt') ? undefined : (json['discardedAt'] === null ? null : new Date(json['discardedAt'])),
        'accessToken': !exists(json, 'accessToken') ? undefined : json['accessToken'],
    };
}

export function TokenToJSON(value?: Token | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'discardedAt': value.discardedAt === undefined ? undefined : (value.discardedAt === null ? null : value.discardedAt.toISOString()),
        'accessToken': value.accessToken,
    };
}

// CUSTOM_CODE_HOOK
